### ISSUE TITLE
Several errors ? 

### ISSUE THREAD

**Issue by f4hbw** [aeburriel/tetrapol-kit#1]
Dear Developpers, 

I get this error when i launch piny_env.sh : 

Using HackRF One with firmware 2014.08.1 
Using Volk machine: ssse3_32_orc
OOOOOO../tetrapol_samples/rec/channel0.bits: No such file or directory
OTraceback (most recent call last):
  File "./demod/tetrapol_rx.py", line 284, in <module>
    auto_tune=options.auto_tune)
  File "./demod/tetrapol_rx.py", line 114, in **init**
    file_sink = blocks.file_sink(gr.sizeof_char, o, False)
  File "/usr/lib/python2.7/dist-packages/gnuradio/blocks/blocks_swig0.py", line 920, in make
    return _blocks_swig0.file_sink_make(_args, *_kwargs)
RuntimeError: can't open file

I use Ubuntu 14.04 with a hackRF One. 

Thanks in advance. Kévin.

**Comment by 0x2b3bfa0** [comment]
Run `mkdir -p ../tetrapol_samples/rec`

This will solve this problem, however I didn't manage to make it work yet...
