### ISSUE TITLE
socket.error: [Errno 98] Address already in use

### ISSUE THREAD

**Issue by f4hbw** [aeburriel/tetrapol-kit#2]
This is the next from the previous error : 

When I have already tried to launch piny_env.py I get this : 

~/tetrapol-kit$ ./piny_env.sh
linux; GNU C++ version 4.8.2; Boost_105400; UHD_003.007.002-0-unknown

Traceback (most recent call last):
  File "./demod/tetrapol_rx.py", line 284, in <module>
    auto_tune=options.auto_tune)
  File "./demod/tetrapol_rx.py", line 63, in **init**
    ("localhost", listen_port), allow_none=True)
  File "/usr/lib/python2.7/SimpleXMLRPCServer.py", line 593, in **init**
    SocketServer.TCPServer.**init**(self, addr, requestHandler, bind_and_activate)
  File "/usr/lib/python2.7/SocketServer.py", line 419, in **init**
    self.server_bind()
  File "/usr/lib/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use

**Comment by 0x2b3bfa0** [comment]
Run `killall python2.7`
