### ISSUE TITLE
TypeError: in method 'source_sptr_set_gain_mode', argument 2 of type 'bool'

### ISSUE THREAD

**Issue by landry76560** [aeburriel/tetrapol-kit#5]
Hello,

I can not find the way to launch the error ./demod.py here I would have help to solve is problem

gr-osmosdr v0.1.4-75-gae686c46 (0.1.5git) gnuradio 3.7.10.1
built-in source types: file fcd rtl rtl_tcp uhd hackrf bladerf rfspace airspy redpitaya 
Using device #0 Realtek RTL2838UHIDIR SN: 00000001
Found Rafael Micro R820T tuner
[R82XX] No valid PLL values for 6000393 Hz!
r82xx_set_freq: failed=-1
Exact sample rate is: 2000000.052982 Hz
Traceback (most recent call last):
  File "./demod.py", line 124, in <module>
    tb = top_block()
  File "./demod.py", line 44, in __init__
    self.src.set_gain_mode(0)
  File "/usr/local/lib/python2.7/dist-packages/osmosdr/osmosdr_swig.py", line 1721, in set_gain_mode
    return _osmosdr_swig.source_sptr_set_gain_mode(self, automatic, chan)
TypeError: in method 'source_sptr_set_gain_mode', argument 2 of type 'bool'

cordialy

**Comment by jswo** [comment]
This is already fixed in upstream (https://github.com/jswo/tetrapol-kit)
